name: Auto send vacancies

on:
  schedule:
     - cron: '0 8 * * *'  
     - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests psycopg2-binary python-dotenv asyncpg
          
      - name: Auto send vacancies
        run: python auto.py
