name: Weekly Parser and Cleanup

on:
  schedule:
    - cron: '0 0 * * 1'  # Каждый понедельник в 00:00 UTC
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests psycopg2-binary python-dotenv
          
      - name: Clean old vacancies (weekly)
        run: python delete_old_vacancies.py
